FROM alpine:3.14

RUN apk update
RUN apk upgrade
RUN apk add --no-cache nginx
RUN apk add --no-cache nginx-mod-rtmp 
RUN apk add --no-cache ffmpeg

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80 1935

CMD [ "nginx", "-g", "daemon off;" ]